### PR TITLE
Fix uri splitting when a / isn't before args

### PR DESCRIPTION
**Pull request by hugglesfox**
Fixes [#129](https://github.com/splashkit/splashkit-core/issues/129)

Tested using the included unit tests.

### CODE REVIEW

**Comment by hugglesfox** [comment]
[Fix URI parsing bug](https://trello.com/c/WmoJmdKf/446-fix-uri-parsing-bug)

**Comment by Wills2022** [comment]
Is the GNU General Public License comment necessary? Splashkit is already licensed under GPL. Otherwise there isn't much further for me to add here. Looks good.  Nice test case.

**Review by Wills2022 — APPROVED** [review]
Is the GNU General Public License comment necessary? Splashkit is already licensed under GPL. Otherwise there isn't much further for me to add here. Looks good. Nice test case.

**Comment by hugglesfox** [comment]
@Wills2022 Thanks for review. In regards to the license preamble, yeah it's against the GPL recommended practices not to include it. I believe (I'm not a lawyer) most of the splashkit source code isn't GPL and is copyright Andrew Cain due to him using his own file preamble
https://www.gnu.org/licenses/gpl-faq.en.html#LicenseCopyOnly

**Review by omckeon — APPROVED** [review]
Excellent

**Pull request merged**
