### PR TITLE
Update SDL version

### PR DESCRIPTION
**Pull request by hugglesfox**
# Description

This is the sibling PR to [splashkit-external#1](https://github.com/thoth-tech/splashkit-external/pull/1). Additionally this PR removes linking to sqlite for windows, removes the prebuilt dependencies for windows (talked to Andrew, these are redundant as we can use the system libraries from Msys2) and updates the cmake minimum version (removes a deprecation warning).

Untested for MacOS

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?

Successfully builds tests on Linux and Windows

## Testing Checklist

- [x] Tested with sktest
- [x] Tested with skunit_tests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Comment by hugglesfox** [comment]
[Fix windows cmake configuration](https://trello.com/c/4LgNo4r5/474-fix-windows-cmake-configuration)

**Comment by hugglesfox** [comment]
[Update CMake version](https://trello.com/c/DBE8HVZ9/453-update-cmake-version)

**Comment by hugglesfox** [comment]
[Update SDL versions](https://trello.com/c/Lx86T7At/438-update-sdl-versions)

**Comment by WhyPenguins** [comment]
Good work! Managed to get this building on Windows too 😄  

Only thing I can see to improve would be to update the list of MinGW dependencies needed in CONTRIBUTING.md (`mingw-w64-x86_64-civetweb`, `mingw-w64-x86_64-SDL2`, `mingw-w64-x86_64-SDL2_gfx` , and so on). I assume macOS ones would also need to be updated?

**Comment by WhyPenguins** [comment]
I'm also interested in whether the following is expected - I think it only affects developers:

The MinGW packages alone are enough to build SplashKit and the tests, and run them from the MSYS2 MINGW64 terminal.

However, the tests won't run by just double clicking the exe, as (at least on my system) the MinGW libraries aren't in the system path. The CONTRIBUTING.md guide says to install SKM too, and this fixes this - it has its own copy of the libraries, and updates PATH to include them.

This seems a bit messy though, since there's now two copies of the libraries on the system, and it seems like it would be possible to link to ones on the MinGW side that aren't compatible with the SKM ones (I think anyway...). I assume that previously the libraries in SKM and splashkit-core were identical so this couldn't be an issue?

It makes me wonder what the expected behavior should be, especially if SKM is being phased out. When developing should we just add the MinGW library directory to our system path?

Sorry if I'm misunderstanding something! Just wanted to check in case this is something we should handle with this PR.

**Review by omckeon — APPROVED** [review]
Incredible work here :)

**Comment by hugglesfox** [comment]
@WhyPenguins sorry I haven't replied sooner. So for windows it still depends on the system libraries and for MacOS there's prebuilt libraries in coresdk/libs. The only thing which splashkit-external is used for is providing the header files at build time, it still links to the system provided libraries. We used to also have prebuilt libraries for windows however Andrew wanted to phase them out in favor of linking to the system provided libraries instead.

For windows we could (and imo should) use the headers provided by the system but msys2 is a little messy in that regards so it's easier to bundle our own headers as we need them for macos anyway.

I agree it is messy and this PR isn't really helping much with that as it's just updating the mess. However my hope is that we can slowly move to a more sane build system. It's just going to take a lot.

**Comment by hugglesfox** [comment]
[Add splashkit dependencies to CMake](https://trello.com/c/Sq081Jca/445-add-splashkit-dependencies-to-cmake)

**Review by omckeon — APPROVED** [review]

**Pull request merged**
