### PR TITLE
Add unit tests for utility functions

### PR DESCRIPTION
**Pull request by matt439**
# Description

There are currently no unit tests for the functions listed under 'Utilities' in the SplashKit documentation. I have created exhaustive tests for each of these functions apart from `display_dialog` as it is generates purely graphical content and would be better suited for `sktests`.

In the process of creating the tests, I have identified issues with `replace_all`, `rnd` and `rnd(min, max)`. I can consistently cause an infinite loop in `replace_all`, and an unhanded exception in the two overloads of `rnd`. Keeping those tests in `skunit_tests` will cause it to fail. As a compromise, I have left the tests in place and commented them. My intention is to create separate pull requests to rectify the faulty functions. Once they are fixed, the tests can be uncommented.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Adding the new tests was achieved by running `cmake -G "Unix Makefiles" .` followed by `make` when in the `/splashkit-core/projects/cmake` directory.

## Testing Checklist

- [x] Tested with skunit_tests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Review by Liquidscroll — APPROVED** [review]
Looks good to me! All tests passed on WSL2. 

However, I think that this should be updated to uncomment the relevant tests, and then ensure this is merged _after_ these functions are fixed. This could occur later, so I'll approve this for now.

**Review by hugglesfox — APPROVED** [review]
Looks good but it might be nice to tag the tests better. For instance tagging all the string related tests with string, the random related tests with random, time related tests with time, resource tests as resource, etc.

Also want to just mention the idea of splitting each section into a separate file though as all the functions tested are in the same source (iirc) then keeping them all in the one file could make sense.

**Review by WhyPenguins — CHANGES_REQUESTED** [review]
This looks good! Just uncomment those tests and this should be good to merge 😃

**Comment by WhyPenguins** [comment]
Ah sorry one more thing, with the latest change to `rnd` the `"min is 1 and max is 0"` test doesn't pass since the logic has changed. Mind updating that test as well? Thanks!

**Comment by matt439** [comment]
I uncommented the tests and fixed the `min is 1 and max is 0` test case.

**Pull request merged**
