### PR TITLE
Add Debian packaging script

### PR DESCRIPTION
**Pull request by hugglesfox**
# Description

This adds the script `tools/scripts/debian/build-deb.sh` which when ran will build `libSplashkit.so` and construct a Debian binary package (`.deb`) which can be installed on any Debian based system.

Building the package itself only requires, in addition to the splashkit build dependencies, ar and tar to be installed. Therefore theoretically one can build the deb using any unix based operating system.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?

The resulting package has been installed on my Debian machine and used to compile and run the splashkit house example.

## Testing Checklist

- [ ] Tested with sktest
- [ ] Tested with skunit_tests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Comment by hugglesfox** [comment]
[Create Debian Package for SplashKit](https://trello.com/c/wXo9Dny0/432-create-debian-package-for-splashkit)

**Comment by Wills2022** [comment]
Looks good so far. If the script has build dependencies (ar, tar) it might be a good idea to specifically list the packages that  these programs are in. I.E. tar, binutils. 

As far as documentation goes it would be a good idea to explicitly state that the script needs to be run from the directory that it lives in, and that it needs sudo. The errors that the script produces without doing these things might be somewhat inscrutable for less technical users. 

I havn't been able to get the binary to compile on my regular testing VM. it gets to about ~95% of the compile and then the VM locks up completely. The VM is able to compile the "normal" splashkit binary as expected. The lockup only seems to happen when running the  build-deb.sh script. Have tried bumping up the VM RAM from 2GB to 8GB. No change. Doing further testing on separate system. Will update.

**Comment by hugglesfox** [comment]
Thanks for the review! I'll add a note about needing to run in the directory it is in as well as clarifying the dependencies.

However it is strange that you needed to run it with sudo. I don't need to on my machine and it wasn't designed with the need to run as the root user. 

I'm thinking the lock up is because it compiles splashkit using all the possible cpu threads (the `-j$nprocs` part). It might not be a bad idea to remove that to ensure it compiles nicely on all machines.

**Comment by Wills2022** [comment]
> However it is strange that you needed to run it with sudo. I don't need to on my machine and it wasn't designed with the need to run as the root user.

Debian is quite picky about it's default $PATH variable. If I had to guess i'd say that there are utilities that the script requires which are not included in the default user $PATH, but are available to super users.

**Comment by hugglesfox** [comment]
> Debian is quite picky about it's default $PATH variable. If I had to guess i'd say that there are utilities that the script requires which are not included in the default user $PATH, but are available to super users.

It only depends on the usual splashkit build tools, tar and binutils.

tar is located in `/bin/tar`, ar is in `/usr/bin/ar`. Both of which are in the path for the user (unlike `/sbin` or `/usr/sbin`).

My guess is that somehow there's a file in your splashkit directory that's owned by root, the first thing it does is compile splashkit which it seems you haven't been able to pass due to the lockup issue? Hence it must be the cmake or make command which is failing. Maybe try 

```shell
cd tools/scripts/cmake/libsplashkit
cmake .
make
```

I've been able to successfully run the script on my Debian machine and Gentoo machine, neither of which required root.

---

Otherwise I've added a readme file (let me know if you think it needs more info on anything) and removed the jobs flag from make.

**Comment by Wills2022** [comment]
> My guess is that somehow there's a file in your splashkit directory that's owned by root, the first thing it does is compile splashkit which it seems you haven't been able to pass due to the lockup issue? Hence it must be the cmake or make command which is failing. Maybe try
> 
> ```shell
> cd tools/scripts/cmake/libsplashkit
> cmake .
> make

This works. I rolled the VM back to a clean state and cloned the repo again. Compiled libsplashkit and then ran the build-deb shell script. No sudo required.

**Review by Wills2022 — APPROVED** [review]

**Review by omckeon — APPROVED** [review]

**Pull request merged**
